### ISSUE TITLE
Error while fetching game data

### ISSUE THREAD

**Issue by Helixable** [1s3k3b/krunker.io.js#41]
```js
(node:9796) UnhandledPromiseRejectionWarning: Error: Game not found.
    at C:\Users\noahg\node_modules\krunker.io.js\src\client\Client.js:102:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9796) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://matchmaker.krunker.io/game-info?game=MIA:w4o1m reason: Unexpected token < in JSON at position 0
    at C:\Users\noahg\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\noahg\node_modules\krunker.io.js\src\client\Client.js:103:53
(node:9796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by Helixable** [comment]
This is my code: 
```js
const krunker = require('krunker.io.js');
const client = new krunker.Client();

client.fetchGame('https://krunker.io/?game=MIA:w4o1m').then(console.log);
```

**Comment by Jytesh** [comment]
Game info doesn't work for most people since, Krunker turned on Cloudfare DDOS protection for all their non-wss endpoints

**Comment by Helixable** [comment]
Oh alright
