### ISSUE TITLE
fetchClan [BUG]

### ISSUE THREAD

**Issue by Hoodgail** [1s3k3b/krunker.io.js#6]
``` 
(node:148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:148) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at new Clan (/rbd/pnpm-volume/ff392d6f-2ef5-40cb-a0a3-2316786089c0/node_modules/.registry.npmjs.org/krunker.io.js/1.2.1/node_modules/krunker.io.js/src/structures/Clan.js:7:35)
    at Promise (/rbd/pnpm-volume/ff392d6f-2ef5-40cb-a0a3-2316786089c0/node_modules/.registry.npmjs.org/krunker.io.js/1.2.1/node_modules/krunker.io.js/src/client/Client.js:45:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``` 
it throws this error

**Comment by 1s3k3b** [comment]
it seems like it's an issue with the game or https://krunker.social/api, neither the game nor the rest API is loading clans.

**Comment by Jytesh** [comment]
It works fine now, for me.

**Comment by Hoodgail** [comment]
> it seems like it's an issue with the game or https://krunker.social/api, neither the game nor the rest API is loading clans.

btw krunker.social is not an official rest api for krunker

**Comment by 1s3k3b** [comment]
closed as it seems like it's not an issue with the lib, but the game or the REST API.
